### ISSUE TITLE
Should unsubscribe be called in onDestroyView or onDestroy?

### ISSUE THREAD

**Issue by mattblang** [vyshane/rex-weather#10]
I'm not sure, I was just curious if there is the chance that `onDestroyView` could have been called but not `onDestroy`, thus resulting in NPE when manipulating UI (the SwipeRefresh in this case).

**Comment by vyshane** [comment]
Yes, you are right. The right thing to do here is to unsubscribe in `onDestroyView`. I'll fix it.

**Comment by mattblang** [comment]
@vyshane Should the initialization of `CompositeSubscription` be in `onCreateView`?  Dan Lew mentioned in [his blog post](http://blog.danlew.net/2014/10/08/grokking-rxjava-part-4/) that once you `unsubscribe` the CompositeSubscription object is unusable.  Should it be initialized again then in `onCreateView` since it is being unsubscribed in `onDestroyView`?
