### ISSUE TITLE
Please using WeatherFragment() but there is not WeatherFragment in this module 

### ISSUE THREAD

**Issue by ajaykeshri** [vyshane/rex-weather#12]
Please using WeatherFragment() but there is not WeatherFragment in this module .
what basically it contain the WeatherFragment()

**Comment by vyshane** [comment]
[`WeatherFragment`](https://github.com/vyshane/rex-weather/blob/master/app/src/main/java/mu/node/rexweather/app/WeatherActivity.java#L70) is an inner class of `WeatherActivity`.

**Comment by ajaykeshri** [comment]
Hi Vyshane
Thanks, I was later on , thank a lot
